Repository SignGin/Clorare, pull requests merged in 2023-04, with the labels that each got.

#11 change data interface
  web/src/pages/reco.tsx
Labels: enhancement

#12 DB 시드 추가
  server/README.md
  server/main/settings.py
  server/restapi/views.py
  server/weatherdata/api.py
  server/weatherdata/management/__init__.py
  server/weatherdata/management/commands/__init__.py
  server/weatherdata/management/commands/add_data.py
  server/weatherdata/models.py
Labels: documentation, enhancement

#13 set real data & modify UI
  web/src/pages/reco.tsx
Labels: enhancement

#16 이미지 수정
  server/.gitignore
  server/README.md
  server/main/media/clothes/cat.jpg
  server/main/media/clothes/navy.jpg
  web/next.config.js
  web/src/pages/reco.tsx
  web/src/utils/constants.ts
Labels: bug, documentation, enhancement

#19 일부 오류처리 추가
  server/restapi/views.py
  server/weatherdata/api.py
Labels: enhancement

#20 Readme Update 및 Error 처리 추가
  README.md
  server/restapi/views.py
  server/weatherdata/api.py
  server/weatherdata/management/commands/add_data.py
Labels: bug, enhancement

#21 update
  README.md
  server/restapi/views.py
Labels: enhancement

#22 Update README.md
  README.md
Labels: documentation
